[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo =  'vim-jp/vimdoc-ja'

# unite
[[plugins]]
repo =  'Shougo/vimproc'
build = 'make'

[[plugins]]
repo =  'Shougo/vimshell'
[[plugins]]
repo =  'Shougo/unite.vim'
[[plugins]]
repo =  'Shougo/neomru.vim'
[[plugins]]
repo =  'Shougo/neoyank.vim'
[[plugins]]
repo =  'Shougo/vimfiler'
[[plugins]]
repo =  'Shougo/neosnippet'
[[plugins]]
repo =  'Shougo/neosnippet-snippets'
[[plugins]]
repo =  't9md/vim-unite-ack'
[[plugins]]
repo =  'Shougo/unite-outline'
[[plugins]]
repo =  'ujihisa/unite-colorscheme'
[[plugins]]
repo =  'tsukkee/unite-tag'
[[plugins]]
repo =  'osyo-manga/unite-quickfix'

## C C++ Objective-C
#[[plugins]]
#repo = Lazy 'https://github.com/tokorom/cocoa.vim.git', 'syntax-only', {'autoload': {'filetypes': ['objc']}}
##[[plugins]]
#repo = Lazy 'https://github.com/tokorom/ctrlp-docset.git', {'autoload': {'filetypes': ['objc']}}
##[[plugins]]
#repo = Lazy 'https://github.com/tokorom/clang_complete.git', 'for-ios', {'autoload': {'filetypes': ['c', 'cpp', 'objc']}}
##[[plugins]]
#repo = Lazy 'https://github.com/tokorom/clang_complete-getopts-ios.git', {'autoload': {'filetypes': ['objc']}}

# web on vim
[[plugins]]
repo =  'choplin/unite-vim_hacks'
[[plugins]]
repo =  'mattn/webapi-vim'
[[plugins]]
repo =  'mattn/wwwrenderer-vim'
[[plugins]]
repo =  'thinca/vim-openbuf'

#
# markdown
[[plugins]]
repo =  'plasticboy/vim-markdown'
[[plugins]]
repo =  'kannokanno/previm'
[[plugins]]
repo =  'tyru/open-browser.vim'

#
# twitter on vim
[[plugins]]
repo =  'basyura/twibill.vim'
[[plugins]]
repo =  'basyura/bitly.vim'
[[plugins]]
repo =  'mattn/favstar-vim'
[[plugins]]
repo =  'basyura/TweetVim'
[[plugins]]
repo =  'yomi322/unite-tweetvim'

#
# syntax
#[[plugins]]
repo =  'othree/html5.vim'
[[plugins]]
repo =  'hail2u/vim-css3-syntax'
[[plugins]]
repo =  'cakebaker/scss-syntax.vim'
#[[plugins]]
repo =  'othree/javascript-libraries-syntax.vim'
#[[plugins]]
repo =  'othree/yajs.vim'
[[plugins]]
repo =  'mxw/vim-jsx'



#
# development:general
[[plugins]]
repo =  'vim-scripts/Align'
[[plugins]]
repo =  'vim-scripts/sudo.vim'
[[plugins]]
repo =  'vim-scripts/catn.vim'
[[plugins]]
repo =  'tyru/caw.vim'
[[plugins]]
repo =  'thinca/vim-ref'
[[plugins]]
repo =  'thinca/vim-qfreplace'
[[plugins]]
repo =  'thinca/vim-quickrun'
[[plugins]]
repo =  'osyo-manga/unite-quickrun_config'
[[plugins]]
repo =  'tpope/vim-surround'
[[plugins]]
repo =  'deton/jasegment.vim'
[[plugins]]
repo =  'scrooloose/syntastic'
[[plugins]]
repo =  'tpope/vim-fugitive'
[[plugins]]
repo =  'fuenor/im_control.vim'
[[plugins]]
repo =  'soramugi/auto-ctags.vim'
[[plugins]]
repo =  'haya14busa/incsearch.vim'
[[plugins]]
repo =  'tmhedberg/matchit'
[[plugins]]
repo =  'deris/vim-rengbang'
[[plugins]]
repo =  'Shougo/neocomplete.vim'

#
# development:frontend
#[[plugins]]
#repo =  'mattn/emmet-vim'
[[plugins]]
repo =  'jiangmiao/simple-javascript-indenter'

#
# development:backend
#[[plugins]]
#repo =  'm2mdas/phpcomplete-extended'
#[[plugins]]
#repo =  'm2mdas/phpcomplete-extended-laravel'
[[plugins]]
repo =  'xsbeats/vim-blade'
[[plugins]]
repo =  'vim-scripts/PDV--phpDocumentor-for-Vim'


# colorscheme
[[plugins]]
repo =  'itchyny/lightline.vim'
[[plugins]]
repo =  'mopp/mopkai.vim'
[[plugins]]
repo =  'reedes/vim-colors-pencil'

#
# others
#[[plugins]]
#repo =  'thinca/vim-threes'
[[plugins]]
repo =  'thinca/vim-scouter'
#[[plugins]]
#repo = Lazy 'supermomonga/jazzradio.vim', { 'depends' : [ 'Shougo/unite.vim' ] }
#
#
#ja
[[plugins]]
repo =  'fuenor/JpFormat.vim'
