# Make sure using latest Homebrew
update
upgrade

tap homebrew/versions
tap homebrew/binary
tap homebrew/dupes
tap sanemat/font
tap phinze/homebrew-cask
tap rcmdnk/homebrew-rcmdnkpac


# Packages
install autoconf
install automake
install binutils
install bash-completion
install brew-cask
install coreutils
install findutils
install lua
install luajit
install git
install mercurial
install pcre
install python
install rbenv
install ruby-build

cask install xquartz
install --vim-powerline ricty
#インストール後、下記の2コマンドを実行
#cp -f /usr/local/Cellar/ricty/3.2.3/share/fonts/Ricty-Bold-Powerline.ttf ~/Library/Fonts
#fc-cache -vf
#
install screenutf8 --utf8
install ssh-copy-id
install the_silver_searcher
install vim --with-lua --with-luajit --without-ruby --override-system-vi
install w3m
install wget

# .dmg
cask install alfred
cask install appcleaner
cask install bettertouchtool
cask install dash
cask install dropbox
cask install evernote
cask install firefox
cask install flash
cask install fluid
cask install google-chrome
cask install google-japanese-ime
cask install iterm2
cask install kobito
cask install libreoffice
cask install path-finder
cask install teamviewer
cask install virtualbox
cask install steermouse

cask install sublime-text
cask install java

cask alfred link
cleanup
