# Make sure using latest Homebrew
update

# Update already-installed formula (takes too much time, I will do it manually later)
# upgrade

# Add Repository
tap homebrew/versions
tap homebrew/dupes
tap homebrew/binary
tap Filriya/homebrew-cask
tap sanemat/font

reinstall --powerline --vim-powerline ricty

# Packages
install autoconf
install automake
install binutils
install bash-completion
install brew-cask
install coreutils
install findutils
install lua
install luajit
install git
install mercurial
install pcre
install python
install rbenv
install ruby-build
install --HEAD -f --use-llvm screen
install ssh-copy-id
install the_silver_searcher
install vim --devel --with-lua
install wget

# .dmg
cask install alfred
cask install appcleaner
cask install bettertouchtool
cask install dash
cask install dropbox
cask install evernote
cask install firefox
cask install flash
cask install fluid
cask install google-chrome
cask install google-chrome-canary
cask install google-drive
cask install google-japanese-ime
cask install iterm2
cask install kobito
cask install keyremap4macbook
cask install libreoffice
cask install path-finder
cask install teamviewer
cask install thunderbird
cask install virtualbox
cask install steermouse



# Remove outdated versions
cleanup
