[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'


#
# development:general
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
[[plugins]]
repo = 'junegunn/fzf.vim'


[[plugins]]
repo = 'Shougo/defx.nvim'
[[plugins]]
repo = 'junegunn/vim-easy-align'
[[plugins]]
repo = 'vim-scripts/sudo.vim'
[[plugins]]
repo = 'vim-scripts/catn.vim'
[[plugins]]
repo = 'tyru/caw.vim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'thinca/vim-qfreplace'
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'machakann/vim-sandwich'
[[plugins]]
repo = 'deton/jasegment.vim'
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
[[plugins]]
repo = 'haya14busa/incsearch.vim'
[[plugins]]
repo = 'haya14busa/incsearch-migemo.vim'
[[plugins]]
repo = 'tpope/vim-repeat'
[[plugins]]
repo = 'tmhedberg/matchit'
[[plugins]]
repo = 'itchyny/vim-parenmatch'
[[plugins]]
repo = 'deris/vim-rengbang'
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
[[plugins]]
repo = 'kana/vim-smartinput'
[[plugins]]
repo = 'honza/vim-snippets'
[[plugins]]
repo = 'reireias/vim-cheatsheet'
[[plugins]]
repo = 'glidenote/memolist.vim'
[[plugins]]
repo = 'majutsushi/tagbar'
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
[[plugins]]
repo = 'LeafCage/yankround.vim'
[[plugins]]
repo = 'MattesGroeger/vim-bookmarks'
[[plugins]]
repo = 'liuchengxu/vista.vim'
[[plugins]]
repo = 'easymotion/vim-easymotion'
[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'osyo-manga/vim-over'
[[plugins]]
repo = 'syui/airsave.vim'


# git
[[plugins]]
repo = 'tpope/vim-fugitive'
# git log
[[plugins]]
repo = 'cohama/agit.vim'
# git branch管理
[[plugins]]
repo = 'idanarye/vim-merginal'
# git commit
[[plugins]]
repo = 'rhysd/committia.vim'
# git 差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'


#
# textobj
# https://github.com/kana/vim-textobj-user/wiki
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'kana/vim-textobj-line' # al
[[plugins]]
repo = 'kana/vim-textobj-entire' # ae
[[plugins]]
repo = 'kana/vim-textobj-function' #af / aF
[[plugins]]
repo = 'kana/vim-textobj-indent' # ai / aI
[[plugins]]
repo = 'kana/vim-textobj-jabraces' # aj{X}
[[plugins]]
repo = 'thinca/vim-textobj-comment' # ac
[[plugins]]
repo = 'lucapette/vim-textobj-underscore' #a_
[[plugins]]
repo = 'sgur/vim-textobj-parameter' #a,
[[plugins]]
repo = 'machakann/vim-textobj-delimited'  #ad aD
[[plugins]]
repo = 'pocke/vim-textobj-markdown' #c
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock' #sb

[[plugins]]
repo = 'terryma/vim-expand-region'


# language server client
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'


# debug adaptor client
# [[plugins]]
# repo = "puremourning/vimspector"
# on_ft = ["php"]
# build = "./install_gadget.py --force-enable-php"
# [[plugins]]
# repo = "puremourning/vimspector"
# on_ft = ["javascript", "bash", "rust"]
# build = "./install_gadget.py"

#
# filetype
[[plugins]]
repo = 'stephpy/vim-yaml'
[[plugins]]
repo = 'cespare/vim-toml'
[[plugins]]
repo = 'vim-scripts/PDV--phpDocumentor-for-Vim'
[[plugins]]
repo = 'neoclide/jsonc.vim'
on_ft = ["jsonc"]
[[plugins]]
repo='vim-scripts/php-annotations-syntax'
on_ft = ["php"]
[[plugins]]
repo='StanAngeloff/php.vim'
on_ft = ["php"]
[[plugins]]
repo='docteurklein/vim-symfony'
on_ft = ["php"]
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ["scss"]
[[plugins]]
repo = 'billyvg/tigris.nvim'
on_ft = ['javascript', 'typescript', 'vue']
hook_post_update = '''
  let g:dein#plugin.build = './install.sh'
'''
[[plugins]]
repo = "pangloss/vim-javascript"
on_ft = ["javascript, typescript"]
[[plugins]]
repo = "leafgarland/typescript-vim"
on_ft = ["javascript, typescript"]
[[plugins]]
repo = "posva/vim-vue"
on_ft = ["vue"]
# [[plugins]]
# repo = "leafOfTree/vim-matchtag"
# on_ft = ["vue"]
# [[plugins]]
# repo = "leafOfTree/vim-vue-plugin"
# on_ft = ["vue"]
[[plugins]]
repo = 'tbastos/vim-lua'
on_ft = ["lua"]
[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = ["csv"]
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ["rust"]
[[plugins]]
repo = 'mhinz/vim-crates'
on_ft = ["toml"]
[[plugins]]
repo = 'robertbasic/vim-hugo-helper'
on_ft = ["hugo"]
[[plugins]]
repo = 'vim-scripts/applescript.vim'
on_ft = ["applescript"]
[[plugins]]
repo = 'kmyk/brainfuck-highlight.vim'
on_ft = ["bf"]
[[plugins]]
repo = 'nelsyeung/twig.vim'
on_ft = ["twig"]

# こいつらonにすると重い
# [[plugins]]
# repo = 'othree/yajs.vim'
# on_ft = ["javascript, typescript"]
# [[plugins]]
# repo = 'othree/es.next.syntax.vim'
# on_ft = ["javascript, typescript"]
# [[plugins]]
# repo = 'othree/javascript-libraries-syntax.vim'
# on_ft = ["javascript, typescript"]
[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = ["nginx"]
[[plugins]]
repo = 'chr4/sslsecure.vim'
on_ft = ["nginx"]

# markdown

[[plugins]]
repo = 'plasticboy/vim-markdown'
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app & yarn install'
[[plugins]]
repo = 'vim-scripts/VOoM'
[[plugins]]
repo = 'habamax/vim-asciidoctor'


# colorscheme
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'mopp/mopkai.vim'
[[plugins]]
repo = 'ayu-theme/ayu-vim'
[[plugins]]
repo = 'drewtempelmeyer/palenight.vim'
[[plugins]]
repo = 'NLKNguyen/papercolor-theme'
[[plugins]]
repo = 'preservim/vim-colors-pencil'
[[plugins]]
repo = 'rakr/vim-one'
[[plugins]]
repo = 'sonph/onehalf'
rtp = 'vim/'
[[plugins]]
repo = 'morhetz/gruvbox'
[[plugins]]
repo = 'rakr/vim-two-firewatch'

# 試してイマイチリスト
# [[plugins]] 
# repo = 'elzr/vim-json'
# [[plugins]]
# repo = 'itchyny/lightline.vim'
# [[plugins]]
# repo = 'yarisgutierrez/ayu-lightline'
# [[plugins]]
# repo = 'yami-beta/lightline-pencil.vim'

[[plugins]]
repo = 'thinca/vim-scouter'

