# [[plugins]]
# repo = 'Shougo/dein.vim'
#
[[plugins]]
repo = 'vim-jp/vimdoc-ja'


# unite
[[plugins]]
repo = 'Shougo/vimproc'
merged = 0
build = 'make'
[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']
[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'
[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/unite-outline'
[[plugins]]
repo = 'ujihisa/unite-colorscheme'
# [[plugins]]
# repo = 'osyo-manga/unite-quickfix'

# 
# development:general
# [[plugins]]
# repo = 'junegunn/fzf'
# build = './install'
# merged = 0
[[plugins]]
repo = 'junegunn/fzf.vim'
[[plugins]]
repo = 'junegunn/vim-easy-align'
[[plugins]]
repo = 'vim-scripts/sudo.vim'
[[plugins]]
repo = 'vim-scripts/catn.vim'
[[plugins]]
repo = 'tyru/caw.vim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'thinca/vim-qfreplace'
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'osyo-manga/unite-quickrun_config'
[[plugins]]
repo = 'machakann/vim-sandwich'
[[plugins]]
repo = 'deton/jasegment.vim'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'fuenor/im_control.vim'
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
[[plugins]]
repo = 'craigemery/vim-autotag'
[[plugins]]
repo = 'haya14busa/vim-migemo'
[[plugins]]
repo = 'haya14busa/incsearch.vim'
[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'
[[plugins]]
repo = 'haya14busa/incsearch-migemo.vim'
[[plugins]]
repo = 'easymotion/vim-easymotion'
[[plugins]]
repo = 'tpope/vim-repeat'
[[plugins]]
repo = 'tmhedberg/matchit'
[[plugins]]
repo = 'deris/vim-rengbang'
[[plugins]]
repo = 'Yggdroot/indentLine'
# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'


#
# textobj
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'kana/vim-textobj-line'
[[plugins]]
repo = 'kana/vim-textobj-entire'
[[plugins]]
repo = 'kana/vim-textobj-function'
[[plugins]]
repo = 'kana/vim-textobj-indent'
[[plugins]]
repo = 'kana/vim-textobj-jabraces'
[[plugins]]
repo = 'lucapette/vim-textobj-underscore'
[[plugins]]
repo = 'sgur/vim-textobj-parameter'
[[plugins]]
repo = 'machakann/vim-textobj-delimited'

[[plugins]]
repo = 'terryma/vim-expand-region'

#
# language server
# [[plugins]]
# repo = 'neoclide/coc.nvim'
# merged = 0
# rev = 'release'
# [[plugins]]
# repo = 'autozimu/LanguageClient-neovim'
# rev = 'next'
# build = 'bash install.sh'
# [[plugins]]
# repo = 'w0rp/ale'
# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# depends = ['nvim-yarp', 'vim-hug-neovim-rpc']
# [[plugins]]
# repo = 'Shougo/neosnippet'
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

#
# filetype
[[plugins]]
repo = 'cespare/vim-toml.git'
[[plugins]]
repo = 'vim-scripts/PDV--phpDocumentor-for-Vim'
[[plugins]]
repo = 'arnaud-lb/vim-php-namespace'
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
[[plugins]]
repo = 'othree/yajs.vim'
[[plugins]]
repo = 'othree/es.next.syntax.vim'
[[plugins]]
repo = 'pangloss/vim-javascript'
[[plugins]]
repo = "posva/vim-vue"
on_ft = ["vue"]
[[plugins]]
repo = "digitaltoad/vim-pug"
on_ft = ["vue", "pug"]
[[plugins]]
repo = 'udalov/kotlin-vim''
on_ft = ["kotlin"]
[[plugins]]
repo = 'tbastos/vim-lua'
on_ft = ["lua"]


#
# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'


# colorscheme
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'mopp/mopkai.vim'
[[plugins]]
repo = 'reedes/vim-colors-pencil'
[[plugins]]
repo = 'ayu-theme/ayu-vim'
[[plugins]]
repo = 'yarisgutierrez/ayu-lightline'
# [[plugins]]
# repo = 'lifepillar/vim-solarized8'


[[plugins]]
repo = 'thinca/vim-scouter'

