[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# unite
[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell'
[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'Shougo/neoyank.vim'
[[plugins]]
repo = 'Shougo/vimfiler'
[[plugins]]
repo = 't9md/vim-unite-ack'
[[plugins]]
repo = 'Shougo/unite-outline'
[[plugins]]
repo = 'ujihisa/unite-colorscheme'
[[plugins]]
repo = 'tsukkee/unite-tag'
[[plugins]]
repo = 'osyo-manga/unite-quickfix'

# web on vim
[[plugins]]
repo = 'choplin/unite-vim_hacks'
[[plugins]]
repo = 'mattn/webapi-vim'
[[plugins]]
repo = 'mattn/wwwrenderer-vim'
[[plugins]]
repo = 'thinca/vim-openbuf'

#
# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'

#
# development:general
[[plugins]]
repo = 'junegunn/vim-easy-align'
[[plugins]]
repo = 'vim-scripts/sudo.vim'
[[plugins]]
repo = 'vim-scripts/catn.vim'
[[plugins]]
repo = 'tyru/caw.vim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'thinca/vim-qfreplace'
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'osyo-manga/unite-quickrun_config'
[[plugins]]
repo = 'machakann/vim-sandwich'
[[plugins]]
repo = 'terryma/vim-expand-region'
[[plugins]]
repo = 'machakann/vim-textobj-delimited'
[[plugins]]
repo = 'deton/jasegment.vim'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'kmnk/vim-unite-giti.git'
[[plugins]]
repo = 'fuenor/im_control.vim'
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
[[plugins]]
repo = 'haya14busa/incsearch.vim'
[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'
[[plugins]]
repo = 'haya14busa/incsearch-migemo.vim'
[[plugins]]
repo = 'easymotion/vim-easymotion'
[[plugins]]
repo = 'tpope/vim-repeat'
[[plugins]]
repo = 'tmhedberg/matchit'
[[plugins]]
repo = 'deris/vim-rengbang'
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# language server
# complete
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'Shougo/deoplete.nvim'
[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'
[[plugins]]
repo = 'Shougo/neosnippet'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#
# development
[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'
[[plugins]]
repo = "posva/vim-vue"
on_ft = ["vue"]
[[plugins]]
repo = "digitaltoad/vim-pug"

[[plugins]]
repo = 'cespare/vim-toml.git'
[[plugins]]
repo = 'vim-scripts/PDV--phpDocumentor-for-Vim'
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
[[plugins]]
repo = 'othree/yajs.vim'
[[plugins]]
repo = 'othree/es.next.syntax.vim'


# colorscheme
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'mopp/mopkai.vim'
[[plugins]]
repo = 'reedes/vim-colors-pencil'

[[plugins]]
repo = 'thinca/vim-scouter'

